### ISSUE TITLE
The EMG and EEG data for 512Hz l download can not be load by np.load

### ISSUE THREAD

**Issue by labmemm** [ncclabsustech/EEGdenoiseNet#5]
this is the .npy,  just contain:/annex/objects/MD5-s36978768--33f28c453964139a5852eca457887b83 in it

**Comment by ncclabsustech** [comment]
Due to size limitations, EEG and EMG epochs with a sample rate of 512hz are temporarily placed in the G-node database (https://gin.g-node.org/NCClab/EEGdenoiseNet).
