### ISSUE TITLE
Signal-to-Noise Ratio calculation

### ISSUE THREAD

**Issue by Gualor** [ncclabsustech/EEGdenoiseNet#6]
Hi!
I'm currently working on a denoising CNN for EOG artifacts. I am implementing a similar procedure to the one described in your paper which cleverly parametrizes the artifact contaminations in the signal by computing the signal with the desired SNR levels to match the physiological ones. 

However I couldn't understand why in the `EEGdenoiseNet/code/benchmark_networks/data_input.py` script you computed the SNR using the RMS instead of the MSE in the ratio.

Line 56 shows:
```python
coe=get_rms(eeg)/(get_rms(noise)*SNR_train[i])
```
meaning that

```python
SNR_train[i]=get_rms(eeg)/(get_rms(noise)*coe)
```

Being the definition of SNR the ratio of powers of signal and noise <img src="https://render.githubusercontent.com/render/math?math=SNR = \frac{P_{signal}}{P_{noise}} =\left( \frac{A_{signal}}{A_{noise}}\right)^2"> shouldn't the SNR be estimated with MSE as <img src="https://render.githubusercontent.com/render/math?math=SNR = \frac{E[S^2]}{E[N^2]} = \frac{\frac{1}{N}\sum{(s^2)}}{\frac{1}{N}\sum{(n^2)}}"> or alternatively using RMS as <img src="https://render.githubusercontent.com/render/math?math=SNR=\left(\frac{\sqrt{\frac{1}{N}\sum{(s^2)}}}{\sqrt{\frac{1}{N}\sum{(n^2)}}}\right)^2">.

Please let me know if I am missing something. Thank you again for your work.

BR

**Comment by ncclabsustech** [comment]
As I know they all can be used to calculate SNR, for example in paper "Canonical Correlation Analysis Applied to Remove Muscle Artifacts From the Electroencephalogram'' and paper "Independent Vector Analysis Applied to Remove Muscle Artifacts in EEG Data"

**Comment by Gualor** [comment]
Hi, thank you for the reply! I will try to be more concise and clear with my question.

I'm using the following additive relationship to describe how noise affects the final signal:    `y = x + k*n` 
where `y` is the noisy EEG signal, `x` is the clean EEG signal, `n` is the noise (EOG or EMG) and `k` is a coefficient to parametrize how much n affects y.

By substituting this relationship inside the definition of SNR we get:

`SNR = MSE(x) / MSE(k*n) = MSE(x) / ((k^2) * MSE(n))`

If we solve the equation for k we get:

`k = sqrt(MSE(x) / (SNR * MSE(n)) = RMS(x) / (RMS(n) * sqrt(SNR))`

Which is different from the equation used in `EEGdenoiseNet/code/benchmark_networks/data_input.py` line 56 where there is no  square root of the SNR in the denominator.

```py
coe=get_rms(eeg)/(get_rms(noise)*SNR_train[i]) 

# Shoud be changed into this:

coe=get_rms(eeg)/(get_rms(noise)*math.sqrt(SNR_train[i]))
```

Please let me know if it is an error on your side or I'm missing something. 

BR

**Comment by ncclabsustech** [comment]
Thanks for your reply!
In this two papers, SNR is defined by:
![cc6bd28be3eb1e59b23e2a906cb8df9](https://user-images.githubusercontent.com/55942031/112319328-eb205c80-8ce8-11eb-9cd8-3dfe97684974.png)
different with
![image](https://user-images.githubusercontent.com/55942031/112319723-4eaa8a00-8ce9-11eb-96b1-927de539e99b.png)
We also feel surprise for this difference, because this 2 paper are important in the area of EEG denoise, so we use the first defination.
Best regards

**Comment by Gualor** [comment]
Thank you, I finally understand now. Have a nice day.

Best regards,
LG
